src/main/java/org/jahia/modules/mailchimp/service/model/MailChimpJahiaList.java
/**
 * ==========================================================================================
 * =                   JAHIA'S DUAL LICENSING - IMPORTANT INFORMATION                       =
 * ==========================================================================================
 *
 *                                 http://www.jahia.com
 *
 *     Copyright (C) 2002-2016 Jahia Solutions Group SA. All rights reserved.
 *
 *     THIS FILE IS AVAILABLE UNDER TWO DIFFERENT LICENSES:
 *     1/GPL OR 2/JSEL
 *
 *     1/ GPL
 *     ==================================================================================
 *
 *     IF YOU DECIDE TO CHOOSE THE GPL LICENSE, YOU MUST COMPLY WITH THE FOLLOWING TERMS:
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 *     2/ JSEL - Commercial and Supported Versions of the program
 *     ===================================================================================
 *
 *     IF YOU DECIDE TO CHOOSE THE JSEL LICENSE, YOU MUST COMPLY WITH THE FOLLOWING TERMS:
 *
 *     Alternatively, commercial and supported versions of the program - also known as
 *     Enterprise Distributions - must be used in accordance with the terms and conditions
 *     contained in a separate written agreement between you and Jahia Solutions Group SA.
 *
 *     If you are unsure which license is appropriate for your use,
 *     please contact the sales department at sales@jahia.com.
 */
package org.jahia.modules.mailchimp.service.model;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import com.ecwid.mailchimp.method.v2_0.lists.ListMethodResult;

/**
 * Created by: Boris
 * Date: 4/24/2015
 * Time: 3:39 PM
 */
public class MailChimpJahiaList {
    protected List<ListMethodResult.Data> remote = new ArrayList<ListMethodResult.Data>();
    protected List<ListMethodResult.Data> local = new ArrayList<ListMethodResult.Data>();
    protected List<String> noLinked = new ArrayList<String>();

    public MailChimpJahiaList(List<ListMethodResult.Data> listsFromAPI, HashSet<String> mappedLists) {
        for (ListMethodResult.Data data : listsFromAPI) {
            if (mappedLists.contains(data.id)) {
                local.add(data);
            } else {
                remote.add(data);
                noLinked.add(data.id);
            }
        }
    }

    public List<ListMethodResult.Data> getRemote() {
        return remote;
    }

    public int getRemoteSize() {
        return remote.size();
    }

    public void setRemote(List<ListMethodResult.Data> remote) {
        this.remote = remote;
    }

    public List<ListMethodResult.Data> getLocal() {
        return local;
    }

    public int getLocalSize() {
        return remote.size();
    }

    public void setLocal(List<ListMethodResult.Data> local) {
        this.local = local;
    }

    public List<String> getNoLinked() {
        return noLinked;
    }

    public void setNoLinked(List<String> noLinked) {
        this.noLinked = noLinked;
    }
}

src/main/resources/jmcim_siteSettingsMailChimp/html/siteSettingsMailChimp.lists.flow/editList.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="functions" uri="http://www.jahia.org/tags/functions" %>
<%@ taglib prefix="jcr" uri="http://www.jahia.org/tags/jcr" %>
<%@ taglib prefix="template" uri="http://www.jahia.org/tags/templateLib" %>
<%@ taglib prefix="uiComponents" uri="http://www.jahia.org/tags/uiComponentsLib" %>
<%@ taglib prefix="utility" uri="http://www.jahia.org/tags/utilityLib" %>

<%--@elvariable id="currentNode" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="list" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="currentResource" type="org.jahia.services.render.Resource"--%>
<%--@elvariable id="out" type="java.io.PrintWriter"--%>
<%--@elvariable id="renderContext" type="org.jahia.services.render.RenderContext"--%>
<%--@elvariable id="script" type="org.jahia.services.render.scripting.Script"--%>
<%--@elvariable id="scriptInfo" type="java.lang.String"--%>
<%--@elvariable id="url" type="org.jahia.services.render.URLGenerator"--%>
<%--@elvariable id="workspace" type="java.lang.String"--%>
<%--@elvariable id="flowExecutionUrl" type="java.lang.String"--%>
<%--@elvariable id="mailchimp" type="org.jahia.modules.mailchimp.service.MailChimpSettings"--%>
    <template:addResources>
        <script type="text/javascript">
            function submitForm(act, value) {
                $('#formAction').val(act);
                if (value) {
                    $('#selectedItemKey').val(value);
                }
                $.fancybox.showLoading();
                $('#flowForm').submit();
            }
            function suscribeFormPreview(currValue) {
                $("#embed-form-display").contents().find('html').html(currValue);
            }
        </script>
    </template:addResources>
    <form action="${flowExecutionUrl}" method="post" style="display: inline;" id="flowForm">
        <input type="hidden" name="selectedItem" value="${listID}"/>
        <input type="hidden" name="_eventId" id="formAction"/>
        <input type="hidden" name="selectedItemKey" id="selectedItemKey"/>
    </form>

<%--
    <div class="clearfix">
        <h1 class="pull-left"><fmt:message key="jmcim_lists.edit"/> - ${renderContext.site.name}</h1>
        <div class="pull-right">
            <img alt="" src="<c:url value="${url.currentModule}/icons/logo_newscript_dark.png"/>"
                 width="178" height="47">
        </div>
    </div>
--%>
    <jcr:node var="list" path="${mailchimp.listsNode.path}/${listID}"/>

    <div class="row-fluid">
        <div class="span3">
            <div class="buttons">
                <button id="addMailChimpList" type="button" class="btn"
                        onclick="submitForm('back')">
                    <i class="icon-backward"> </i>&nbsp;<fmt:message key="jmcim_back"/></button>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <h2>${list.displayableName}  - <fmt:message key="jmcim_lists.manage_list"/> <a href="https://${mailchimp.apiPrefix}admin.mailchimp.com/lists/members/?id=${listID}" target="_blank">MailChimp</a></h2>

    <div class="box-1">
        <%@include file="../messages.inc" %>

        <c:set var="welcome" value="${list.propertiesAsString['welcome']==null ? 'no' : list.propertiesAsString['welcome']}"/>
        <fieldset>
            <h2><fmt:message key="jmcim_lists.options"/></h2>
            <label for="noWelcome" class="checkbox">
                <input type="radio" name="doubleOptin" id="noWelcome" onclick="submitForm('noWelcome',$(this).attr('checked')!='checked');"
                     <c:if test="${welcome == 'no'}">checked="checked"</c:if>/>
                <fmt:message key="jmcim_lists.noWelcome"/>
            </label>
            <div class="clear"></div>
            <label for="confirmationWelcome" class="checkbox">
                <input type="radio" name="confirmation" id="confirmationWelcome" onclick="submitForm('confirmationWelcome',$(this).attr('checked')!='checked');"
                       <c:if test="${welcome == 'confirmation'}">checked="checked"</c:if>/>
                <fmt:message key="jmcim_lists.confirmationOptin"/>
            </label>
            <div class="clear"></div>
            <label for="sendWelcome" class="checkbox">
                <input type="radio" name="sendWelcome" id="sendWelcome" onclick="submitForm('sendWelcome',$(this).attr('checked')!='checked');"
                       <c:if test="${welcome == 'welcome'}">checked="checked"</c:if>/>
                <fmt:message key="jmcim_lists.sendWelcome"/>
            </label>
            <div class="clear"></div>
            <h2><fmt:message key="jmcim_lists.list_integration"/></h2>
            <label for="setWebhook" class="checkbox">
                <input type="checkbox" name="setWebhook" id="setWebhook" onclick="submitForm('setWebhook',$(this).attr('checked')!='checked');"
                       <c:if test="${not empty list.propertiesAsString['webhookUrl'] }">checked="checked"</c:if>/>
                <fmt:message key="jmcim_lists.setWebhook"/>
            </label>
            <div class="clear"></div>
    </fieldset>
    </div>
    <div class="box-1">
        <fieldset>
            <h2><fmt:message key="jmcim_lists.varFields"/></h2>
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th width="3%">#</th>
                    <th><fmt:message key="jmcim_listsFields.name"/></th>
                    <th><fmt:message key="jmcim_listsFields.tag"/></th>
                    <th><fmt:message key="jmcim_listsFields.jahiaField"/></th>
                    <th width="25%"><fmt:message key="label.actions"/></th>
                </tr>
                </thead>
                <tbody>
                <c:forEach items="${varFields.local}" var="field" varStatus="loopStatus">
                    <tr>
                        <td>${loopStatus.index+1}</td>
                        <td>${field.vars.name}</td>
                        <td>${field.key}</td>
                        <td>${field.value}</td>
                        <td><c:if test="${not field.vars.req}">
                            <a style="margin-bottom:0;" class="btn btn-danger btn-small" title="${i18nRemove}" href="#delete" onclick="submitForm('remfieldAction','${field.key}');">
                                <i class="icon-remove icon-white"></i>
                            </a>
                            </c:if>
                        </td>
                    </tr>
                </c:forEach>
                </tbody>
            </table>
            <c:if test="${fn:length(varFields.remote) > 0 }">
            <button class="btn btn-primary" onclick="$('#addFieldFormWrap').toggle();return false;">
                <i class="icon-plus  icon-white"></i>&nbsp;&nbsp;<fmt:message key="jmcim_listsFields.add"/>
            </button>
            </c:if>
        </fieldset>
    </div>
    <div class="box-1"  id="addFieldFormWrap" style="display: none;">
        <fieldset>
            <form id="updateSiteForm" action="${flowExecutionUrl}" method="post">
                <input type="hidden" name="_eventId" id="addfieldAction" value="addfieldAction"/>
                <input type="hidden" name="selectedItem" value="${listID}"/>
                <div class="input-append">
                <select name="selectedItemKey" id="remote_lists">
                    <c:forEach items="${varFields.remote}" var="field" varStatus="loopStatus">
                        <option value="${field.vars.tag}">${field.vars.name}</option>
                    </c:forEach>
                </select>
                    <input type="text" name="selectedItemValue" id="newVarFieldValue" value="" size="10">
                    <button title="Add" class="btn btn-primary" type="button" id="addVarField" onclick="$('#updateSiteForm').submit();">
                        <i class="icon-plus icon-white"></i>
                    </button>
                </div>
               <%-- <button class="btn btn-primary" type="button" onclick="addLists();"><i class="icon-plus icon-white"></i></button>--%>
            </form>
        </fieldset>
    </div>
<div class="box-1">
    <fieldset>
        <h2><fmt:message key="jmcim_webhook"/></h2>
        <c:if test="${fn:length(webhooks)>0}">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <th width="3%">#</th>
                <th><fmt:message key="jmcim_webhook.j_url"/></th>
                <th><fmt:message key="jmcim_webhook.j_actions"/></th>
                <th><fmt:message key="jmcim_webhook.j_sources"/></th>
                <th width="25%"><fmt:message key="label.actions"/></th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${webhooks}" var="webhook" varStatus="loopStatus">
                <tr>
                    <td>${loopStatus.index+1}</td>
                    <td>${webhook.url}</td>
                    <td><span title="${webhook.actionsHint}">${webhook.actionsStr}</span></td>
                    <td><span title="${webhook.sourcesHint}">${webhook.sourcesStr}</span></td>
                    <td>
                        <c:if test="${not webhook.special}">
                        <a style="margin-bottom:0;" class="btn btn-small" title="${i18nEdit}" href="#edit" onclick="submitForm('editWebhookAction','${webhook.url}')">
                            <i class="icon-pencil"></i>
                        </a>
                        <a style="margin-bottom:0;" class="btn btn-danger btn-small" title="${i18nRemove}" href="#delete" onclick="submitForm('remWebhookAction','${webhook.url}');">
                            <i class="icon-remove icon-white"></i>
                        </a>
                        </c:if>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
        </c:if>
        <button class="btn btn-primary" onclick="submitForm('addWebhookAction')">
            <i class="icon-plus  icon-white"></i>&nbsp;&nbsp;<fmt:message key="jmcim_webhook.add"/>
        </button>
    </fieldset>
</div>

src/main/resources/jmcim_siteSettingsMailChimp/html/siteSettingsMailChimp.lists.flow/editWebhook.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="functions" uri="http://www.jahia.org/tags/functions" %>
<%@ taglib prefix="jcr" uri="http://www.jahia.org/tags/jcr" %>
<%@ taglib prefix="template" uri="http://www.jahia.org/tags/templateLib" %>
<%@ taglib prefix="uiComponents" uri="http://www.jahia.org/tags/uiComponentsLib" %>
<%@ taglib prefix="utility" uri="http://www.jahia.org/tags/utilityLib" %>

<%--@elvariable id="currentNode" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="currentResource" type="org.jahia.services.render.Resource"--%>
<%--@elvariable id="out" type="java.io.PrintWriter"--%>
<%--@elvariable id="renderContext" type="org.jahia.services.render.RenderContext"--%>
<%--@elvariable id="script" type="org.jahia.services.render.scripting.Script"--%>
<%--@elvariable id="scriptInfo" type="java.lang.String"--%>
<%--@elvariable id="url" type="org.jahia.services.render.URLGenerator"--%>
<%--@elvariable id="workspace" type="java.lang.String"--%>
<%--@elvariable id="flowExecutionUrl" type="java.lang.String"--%>
<%--@elvariable id="mailchimp" type="org.jahia.modules.mailchimp.service.MailChimpSettings"--%>

<template:addResources>
    <script type="text/javascript">
        function submitForm(act, value) {
            $('#formAction').val(act);
            $('#webhookUrl').removeAttr("disabled");
            $('#flowForm').submit();
        }
    </script>
</template:addResources>
<form action="${flowExecutionUrl}" method="post" style="display: inline;" id="flowForm">
    <input type="hidden" name="selectedItem" value="${listID}"/>
    <input type="hidden" name="_eventId" id="formAction"/>
    <input type="hidden" name="selectedItemKey" id="selectedItemKey"/>

    <div class="box-1">
    <legend><fmt:message key="jmcim_webhook"/></legend>
    <%@include file="../messages.inc" %>
    <fieldset>
        <div class="control-group">
            <h2><fmt:message key="jmcim_webhook.j_url"/></h2>
            <div class="controls">
                <input id="webhookUrl" name="webhookurl" type="text"  lang="44"
                       <c:if test="${fn:length(webhook.url)>0}">
                       value="${webhook.url}" disabled="disabled"
                       </c:if>
                        />
            </div>
        </div>
    </fieldset>
    <fieldset>
        <h2><fmt:message key="jmcim_webhook.j_actions"/></h2>
        <label for="subscribe" class="checkbox">
            <input type="checkbox" name="subscribe" id="subscribe" <c:if test="${webhook.actions.subscribe}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_actions.j_subscribe"/>
        </label>
        <div class="clear"></div>
        <label for="unsubscribe" class="checkbox">
            <input type="checkbox" name="unsubscribe" id="unsubscribe" <c:if test="${webhook.actions.unsubscribe}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_actions.j_unsubscribe"/>
        </label>
        <div class="clear"></div>
        <label for="profile" class="checkbox">
            <input type="checkbox" name="profile" id="profile" <c:if test="${webhook.actions.profile}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_actions.j_profile"/>
        </label>
        <div class="clear"></div>
        <label for="cleaned" class="checkbox">
            <input type="checkbox" name="cleaned" id="cleaned" <c:if test="${webhook.actions.cleaned}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_actions.j_cleaned"/>
        </label>
        <div class="clear"></div>
        <label for="upemail" class="checkbox">
            <input type="checkbox" name="upemail" id="upemail" <c:if test="${webhook.actions.upemail}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_actions.j_upemail"/>
        </label>
        <div class="clear"></div>
        <label for="campaign" class="checkbox">
            <input type="checkbox" name="campaign" id="campaign" <c:if test="${webhook.actions.campaign}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_actions.j_campaign"/>
        </label>
        <div class="clear"></div>
    </fieldset>
    <fieldset>
        <h2><fmt:message key="jmcim_webhook.j_sources"/></h2>
        <label for="user" class="checkbox">
            <input type="checkbox" name="user" id="user" <c:if test="${webhook.sources.user}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_sources.j_user"/>
        </label>
        <div class="clear"></div>
        <label for="admin" class="checkbox">
            <input type="checkbox" name="admin" id="admin" <c:if test="${webhook.sources.admin}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_sources.j_admin"/>
        </label>
        <div class="clear"></div>
        <label for="api" class="checkbox">
            <input type="checkbox" name="api" id="api" <c:if test="${webhook.sources.api}">checked="checked"</c:if>/>
            <fmt:message key="jmcim_webhook.j_sources.j_api"/>
        </label>
        <div class="clear"></div>
    </fieldset>
    <div class="buttons">

    <button id="saveWebhook" type="button" class="btn btn-primary"
                onclick="submitForm('saveWebhookAction');">
            <fmt:message key="label.save"/>
        </button>
        <button id="cancelWebhook" type="button" class="btn btn-primary"
            onclick="submitForm('backToList')">
        <fmt:message key="label.cancel"/>
    </button>
    </div>
</div>
</form>

src/main/resources/jmcim_siteSettingsMailChimp/html/siteSettingsMailChimp.lists.flow/manageLists.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="functions" uri="http://www.jahia.org/tags/functions" %>
<%@ taglib prefix="jcr" uri="http://www.jahia.org/tags/jcr" %>
<%@ taglib prefix="template" uri="http://www.jahia.org/tags/templateLib" %>
<%@ taglib prefix="uiComponents" uri="http://www.jahia.org/tags/uiComponentsLib" %>
<%@ taglib prefix="utility" uri="http://www.jahia.org/tags/utilityLib" %>
<%@ taglib prefix="jmcim" uri="http://www.jahia.org/tags/jmcim" %>

<%--@elvariable id="currentNode" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="currentResource" type="org.jahia.services.render.Resource"--%>
<%--@elvariable id="out" type="java.io.PrintWriter"--%>
<%--@elvariable id="renderContext" type="org.jahia.services.render.RenderContext"--%>
<%--@elvariable id="script" type="org.jahia.services.render.scripting.Script"--%>
<%--@elvariable id="scriptInfo" type="java.lang.String"--%>
<%--@elvariable id="url" type="org.jahia.services.render.URLGenerator"--%>
<%--@elvariable id="workspace" type="java.lang.String"--%>
<%--@elvariable id="flowExecutionUrl" type="java.lang.String"--%>
<%--@elvariable id="mailchimp" type="org.jahia.modules.mailchimp.service.MailChimpSettings"--%>

<%@include file="../i18n.inc"%>

    <c:set var="lists" value="${mailchimp.listsSync}"/>
    <template:addResources>
        <script type="text/javascript">
            function submitForm(act, value) {
                $.fancybox.showLoading();
                $('#formAction').val(act);
                if (value) {
                    $('#selectedItem').val(value);
                }
                $('#flowForm').submit();
            }
        </script>
    </template:addResources>
    <form action="${flowExecutionUrl}" method="post" style="display: inline;" id="flowForm">
        <input type="hidden" name="selectedItem" id="selectedItem"/>
        <input type="hidden" name="_eventId" id="formAction"/>
    </form>

    <h2><fmt:message key="jmcim_lists.manage_lists"/> <a href="https://${mailchimp.apiPrefix}admin.mailchimp.com/lists/" target="_blank">MailChimp</a></h2>

    <div class="row-fluid">
        <div class="span3">
            <div class="buttons">
                <button id="addMailChimpList" type="button" class="btn"
                        onclick="open('https://${mailchimp.apiPrefix}admin.mailchimp.com/lists/new-list/', '','', true)">
                    <i class="icon-plus"> </i><fmt:message key="jmcim_lists.create"/></button>
                <div class="clear"></div>
            </div>
        </div>
    </div>

<div class="box-1">
    <%@include file="../messages.inc" %>
    <fieldset>
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th width="3%">#</th>
            <th><fmt:message key="imcim_lists.name"/></th>
            <th><fmt:message key="imcim_lists.email_option"/></th>
            <th><fmt:message key="imcim_lists.rating"/></th>
            <th><fmt:message key="imcim_lists.member_count"/></th>
            <th><fmt:message key="imcim_lists.unsubscribe_count"/></th>
            <th><fmt:message key="imcim_lists.cleaned_count"/></th>
            <th width="25%"><fmt:message key="label.actions"/></th>
        </tr>
        </thead>
        <tbody>
        <c:forEach items="${lists.local}" var="list" varStatus="loopStatus">
            <tr>
                <td>${loopStatus.index+1}</td>
                <td>${list.name}</td>
                <td>${list.email_type_option}</td>
                <td><fmt:formatNumber type="number" value="${list.list_rating}"/></td>
                <td><fmt:formatNumber type="number" value="${list.stats.member_count}"/></td>
                <td><fmt:formatNumber type="number" value="${list.stats.unsubscribe_count}"/></td>
                <td><fmt:formatNumber type="number" value="${list.stats.cleaned_count}"/></td>
                <td>
                    <a style="margin-bottom:0;" class="btn btn-small" title="${i18nEdit}" href="#edit"
                       onclick="submitForm('editListAction','${list.id}')">
                        <i class="icon-pencil"></i>
                    </a>
                    <a style="margin-bottom:0;" class="btn btn-small" title="${i18nEditMailChimp}" href="https://${mailchimp.apiPrefix}admin.mailchimp.com/lists/members/?id=${list.web_id}" target="_blank">
                        <i class="icon-share-alt"></i>
                    </a>
                    <a style="margin-bottom:0;" class="btn btn-danger btn-small" title="${i18nRemove}" href="#delete" onclick="submitForm('removeListAction','${list.id}');">
                        <i class="icon-remove icon-white"></i>
                    </a>
                </td>
            </tr>
        </c:forEach>
        </tbody>
    </table>
        <button class="btn btn-primary" onclick="$('#updateSiteFormWrap').toggle(); return false;">
            <i class="icon-plus  icon-white"></i>&nbsp;&nbsp;<fmt:message key="jmcim_lists.add"/>
        </button>
    </fieldset>
</div>
    <div class="box-1"  id="updateSiteFormWrap" style="display: ${data.listIds==null? 'none' : 'block' };">
        <fieldset>
            <form id="updateSiteForm" action="${flowExecutionUrl}" onsubmit="$.fancybox.showLoading(); return true;"  method="post">
                <input type="hidden" name="_eventId" value="mapListAction"/>
                <form:select path="data.listIds" id="remote_lists" multiple="multiple" size="${lists.remoteSize+1}">
                    <c:forEach var="mcList" items="${lists.remote}">
                        <form:option value="${mcList.id}" >${mcList.name} (<fmt:formatNumber type="number" value="${mcList.stats.member_count}"/>)</form:option>
                    </c:forEach>
                </form:select>
                <button class="btn btn-primary" type="submit"><i class="icon-plus icon-white"></i></button>
            </form>
        </fieldset>
    </div>
