src/main/java/org/jahia/modules/mailchimp/sitesettings/model/TemplateModel.java
/**
 * ==========================================================================================
 * =                   JAHIA'S DUAL LICENSING - IMPORTANT INFORMATION                       =
 * ==========================================================================================
 *
 *                                 http://www.jahia.com
 *
 *     Copyright (C) 2002-2016 Jahia Solutions Group SA. All rights reserved.
 *
 *     THIS FILE IS AVAILABLE UNDER TWO DIFFERENT LICENSES:
 *     1/GPL OR 2/JSEL
 *
 *     1/ GPL
 *     ==================================================================================
 *
 *     IF YOU DECIDE TO CHOOSE THE GPL LICENSE, YOU MUST COMPLY WITH THE FOLLOWING TERMS:
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 *     2/ JSEL - Commercial and Supported Versions of the program
 *     ===================================================================================
 *
 *     IF YOU DECIDE TO CHOOSE THE JSEL LICENSE, YOU MUST COMPLY WITH THE FOLLOWING TERMS:
 *
 *     Alternatively, commercial and supported versions of the program - also known as
 *     Enterprise Distributions - must be used in accordance with the terms and conditions
 *     contained in a separate written agreement between you and Jahia Solutions Group SA.
 *
 *     If you are unsure which license is appropriate for your use,
 *     please contact the sales department at sales@jahia.com.
 */
package org.jahia.modules.mailchimp.sitesettings.model;

import org.jahia.services.content.JCRNodeWrapper;

import javax.jcr.RepositoryException;
import java.io.Serializable;

/**
 * Created by: Boris
 * Date: 4/24/2015
 * Time: 7:02 AM
 */
public class TemplateModel implements Serializable {
    String templateUUID;
    String title;
    String contentNode;
    String contentNodeDecoy;
    boolean isUpdate = false;
    boolean restore = false;
    boolean showRestore = false;

    public TemplateModel(JCRNodeWrapper node) throws RepositoryException {
        setTemplateUUID(node.getIdentifier());
        setTitle(node.getPropertyAsString("jcr:title"));
        setUpdate(true);
        JCRNodeWrapper contentNode = (JCRNodeWrapper) node.getProperty("contentNode").getNode();
        setContentNode(contentNode.getIdentifier());
        setContentNodeDecoy(contentNode.getDisplayableName());
    }

    public TemplateModel() {
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContentNode() {
        return contentNode;
    }

    public void setContentNode(String contentNode) {
        this.contentNode = contentNode;
    }

    public String getContentNodeDecoy() {
        return contentNodeDecoy;
    }

    public void setContentNodeDecoy(String contentNodeDecoy) {
        this.contentNodeDecoy = contentNodeDecoy;
    }

    public boolean isUpdate() {
        return isUpdate;
    }

    public void setUpdate(boolean isUpdate) {
        this.isUpdate = isUpdate;
    }

    public String getTemplateUUID() {
        return templateUUID;
    }

    public void setTemplateUUID(String templateUUID) {
        this.templateUUID = templateUUID;
    }

    public boolean isRestore() {
        return restore;
    }

    public void setRestore(boolean restore) {
        this.restore = restore;
    }

    public boolean isShowRestore() {
        return showRestore;
    }

    public void setShowRestore(boolean showRestore) {
        this.showRestore = showRestore;
    }
}

src/main/resources/jmcim_siteSettingsMailChimp/html/siteSettingsMailChimp.campaigns.flow/formCampaignSet.jsp
<%@ page language="java" contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="template" uri="http://www.jahia.org/tags/templateLib" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="jcr" uri="http://www.jahia.org/tags/jcr" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="functions" uri="http://www.jahia.org/tags/functions" %>
<%@ taglib prefix="user" uri="http://www.jahia.org/tags/user" %>
<%@ taglib prefix="ui" uri="http://www.jahia.org/tags/uiComponentsLib" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="var" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="jmcim" uri="http://www.jahia.org/tags/jmcim" %>

<%--@elvariable id="currentNode" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="out" type="java.io.PrintWriter"--%>
<%--@elvariable id="script" type="org.jahia.services.render.scripting.Script"--%>
<%--@elvariable id="scriptInfo" type="java.lang.String"--%>
<%--@elvariable id="workspace" type="java.lang.String"--%>
<%--@elvariable id="renderContext" type="org.jahia.services.render.RenderContext"--%>
<%--@elvariable id="currentResource" type="org.jahia.services.render.Resource"--%>
<%--@elvariable id="url" type="org.jahia.services.render.URLGenerator"--%>
<%--@elvariable id="mailSettings" type="org.jahia.services.mail.MailSettings"--%>
<%--@elvariable id="flowRequestContext" type="org.springframework.webflow.execution.RequestContext"--%>
<%--@elvariable id="flowExecutionUrl" type="java.lang.String"--%>
<%--@elvariable id="template" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="newslettersRootNode" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="mailchimp" type="org.jahia.modules.mailchimp.service.MailChimpSettings"--%>
<%--@elvariable id="csm" type="org.jahia.modules.mailchimp.sitesettings.model.CampaignSetModel"--%>
<c:set value="${jmcim:settings(renderContext.mainResource.node)}" var="mailchimp" scope="request"/>

<template:addResources type="css" resources="newsletter-settings.css"/>

<fmt:message var="i18nNameMandatory" key="jmcim_template.errors.name.mandatory"/><c:set var="i18nNameMandatory" value="${fn:escapeXml(i18nNameMandatory)}"/>
<fmt:message var="i18nContentNodeMandatory" key="jmcim_template.errors.contentNode.mandatory"/><c:set var="i18nContentNodeMandatory" value="${fn:escapeXml(i18nContentNodeMandatory)}"/>

<fmt:message var="i18nSubject" key="jmcim_campaigns.errors.subject"/><c:set var="i18nSubject" value="${fn:escapeXml(i18nSubject)}"/>
<fmt:message var="i18nFromEmail" key="jmcim_campaigns.errors.fromEmail"/><c:set var="i18nFromEmail" value="${fn:escapeXml(i18nFromEmail)}"/>
<fmt:message var="i18nFromName" key="jmcim_campaigns.errors.fromName"/><c:set var="i18nFromName" value="${fn:escapeXml(i18nFromName)}"/>
<fmt:message var="i18nToName" key="jmcim_campaigns.errors.toName"/><c:set var="i18nToName" value="${fn:escapeXml(i18nToName)}"/>
<fmt:message var="i18nList" key="jmcim_campaigns.errors.list"/><c:set var="i18nList" value="${fn:escapeXml(i18nList)}"/>



<c:set var="isUpdate" value="${csm.update}"/>


<template:addResources>
    <script type="text/javascript">
    function showCampaignSetErrors(messages, separator) {
        var message = "";
        for(var i = 0; i < messages.length; i++){
            if(i == 0){
                message = messages[i];
            }else {
                message += (separator + messages[i]);
            }
        }
        $("#campaignSetFormErrorMessages").html(message);
        $("#campaignSetFormErrorContainer").show();
    }

    function hideTemplateErrors() {
        $("#campaignSetFormErrorMessages").empty();
        $("#campaignSetFormErrorContainer").hide();
    }

    function submitCampaignSetForm(act) {
        $('#campaignSetFormAction').val(act);
        $('#campaignSetForm').submit();
    }

    $(document).ready(function() {
        $("#campaignSetFormErrorClose").bind("click", function(){
            hideTemplateErrors();
        });
        $('#campaignSetForm').submit(function () {
            if ($('#campaignSetFormAction').val()=='cancel')
                return true;
            // validate fields
            var messages = [];
            if (!$("#campaignSetTitle").val().trim()) {
                messages.push("${i18nNameMandatory}");
            }
            if (!$("#campaignSetSubject").val() && messages.length < 1) {
                messages.push("${i18nSubject}");
            }
            if (!$("#campaignSetFromEmail").val() && messages.length < 1) {
                messages.push("${i18nFromEmail}");
            }
            if (!$("#campaignSetFromName").val() && messages.length < 1) {
                messages.push("${i18nFromName}");
            }
            if (!$("#campaignSetToName").val() && messages.length < 1) {
                messages.push("${i18nToName}");
            }
            if (!$("#listNode").val() && messages.length < 1) {
                messages.push("${i18nList}");
            }
            if (!$("#contentNode").val() && messages.length < 1) {
                messages.push("${i18nContentNodeMandatory}");
            }



            if (messages.length>0) {
                showCampaignSetErrors(messages, "</br>");
                return false;
            }
            $.fancybox.showLoading();
            return true;
        })
    });

    </script>
</template:addResources>

<div>
    <c:choose>
        <c:when test="${isUpdate}">
            <h2><fmt:message key="jmcim_campaigns.edit"/> - ${fn:escapeXml(csm.title)}</h2>
        </c:when>
        <c:otherwise>
            <h2><fmt:message key="jmcim_campaigns.add"/></h2>
        </c:otherwise>
    </c:choose>

    <div class="box-1">
        <div class="alert alert-error" style="display: none" id="campaignSetFormErrorContainer">
            <button type="button" class="close" id="campaignSetFormErrorClose">&times;</button>
            <span id="campaignSetFormErrorMessages"></span>
        </div>
        <c:forEach items="${flowRequestContext.messageContext.allMessages}" var="message">
            <c:if test="${message.severity eq 'INFO'}">
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                        ${message.text}
                </div>
            </c:if>
            <c:if test="${message.severity eq 'ERROR'}">
                <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                        ${message.text}
                </div>
            </c:if>
        </c:forEach>
        <form action="${flowExecutionUrl}" method="POST" id="campaignSetForm">
            <input type="hidden" name="_eventId" id="campaignSetFormAction" value="ok"/>
            <input type="hidden" name="campaignSetUUID" value="${campaignSetUUID}"/>
            <fieldset>
                <div class="container-fluid">
                    <div class="row-fluid">
                        <div class="span6">
                            <label for="campaignSetTitle"><fmt:message key="label.name"/> <span class="text-error"><strong>*</strong></span></label>
                            <form:input path="csm.title" id="campaignSetTitle" />
                        </div>
                        <div class="span6">
                            <label for="campaignSetSubject"><fmt:message key="jmcim_campaigns.subject"/> <span class="text-error"><strong>*</strong></span></label>
                            <form:input path="csm.subject" id="campaignSetSubject" />
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <label for="campaignSetFromEmail"><fmt:message key="jmcim_campaigns.fromEmail"/> <span class="text-error"><strong>*</strong></span></label>
                            <form:input path="csm.fromEmail" id="campaignSetFromEmail" />
                        </div>
                        <div class="span6">
                            <label for="campaignSetFromName"><fmt:message key="jmcim_campaigns.fromName"/> <span class="text-error"><strong>*</strong></span></label>
                            <form:input path="csm.fromName" id="campaignSetFromName" />
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <label for="campaignSetToName"><fmt:message key="jmcim_campaigns.toName"/> <span class="text-error"><strong>*</strong></span></label>
                            <form:input path="csm.toName" id="campaignSetToName" />
                        </div>
                        <div class="span6">
                            <label for="listNode"><fmt:message key="jmcim_campaigns.list"/> <span class="text-error"><strong>*</strong></span></label>
                            <c:if test="${csm.listId != null}">
                                <jcr:node var="listDecoy" uuid="${csm.listId}"/>
                            </c:if>
                            <input value="${listDecoy == null ? '' : listDecoy.displayableName}" disabled="true" type="text" id="listIdDecoy" class="left"/>
                            <div class="left picker">
                                <form:input path="csm.listId" type="hidden" id="listNode"/>
                                <ui:treeItemSelector fieldId="listNode" displayFieldId="listIdDecoy"
                                                     displayIncludeChildren="false" valueType="identifier"
                                                     selectableNodeTypes="jmcim:List"
                                                     nodeTypes="jmcim:List"
                                                     root="${mailchimp.listRootPath}" />
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <label for="contentNode"><fmt:message key="jmcim_campaigns.contentNode"/> <span class="text-error"><strong>*</strong></span></label>
                            <form:input disabled="true" path="csm.contentNodeDecoy" type="text" id="contentNodeDecoy" name="contentNodeDecoy" class="left"/>
                            <div class="left picker">
                                <form:input path="csm.contentNode" type="hidden" id="contentNode"/>
                                <ui:treeItemSelector fieldId="contentNode" displayFieldId="contentNodeDecoy"
                                                     displayIncludeChildren="false" valueType="identifier"
                                                     selectableNodeTypes="jmix:hasTemplateNode"
                                                     nodeTypes="jmix:hasTemplateNode,jmix:visibleInPagesTree"/>
                            </div>
                        </div>
                        <div class="span6">
                            <label for="campaignSetScheduler"><fmt:message key="jmcim_campaigns.scheduler.info"/> </label>
                            <form:input path="csm.scheduler" id="campaignSetScheduler" /><br/>
                            <form:checkbox path="csm.autoSend"/>&nbsp;<fmt:message key="jmcim_campaigns.autoSend"/>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <label for="campaignSetCleanPeriod"><fmt:message
                                    key="jmcim_campaigns.scheduler.delete"/> </label>
                            <form:input path="csm.cleanPeriodStr" id="campaignSetCleanPeriod"/><br/>
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset><br/>
                <div class="container-fluid">
                    <div class="row-fluid">
                        <div class="span12">
                            <button class="btn btn-primary">
                                <i class="icon-${isUpdate ? 'share' : 'plus'} icon-white"></i>
                                &nbsp;<fmt:message key="label.${isUpdate ? 'update' : 'add'}"/>
                            </button>
                            <button class="btn" onclick="submitCampaignSetForm('cancel'); return false;">
                                <i class="icon-ban-circle"></i>
                                &nbsp;<fmt:message key="label.cancel"/>
                            </button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

src/main/resources/jmcim_siteSettingsMailChimp/html/siteSettingsMailChimp.campaigns.flow/manageCampaignSets.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="functions" uri="http://www.jahia.org/tags/functions" %>
<%@ taglib prefix="jcr" uri="http://www.jahia.org/tags/jcr" %>
<%@ taglib prefix="template" uri="http://www.jahia.org/tags/templateLib" %>
<%@ taglib prefix="uiComponents" uri="http://www.jahia.org/tags/uiComponentsLib" %>
<%@ taglib prefix="utility" uri="http://www.jahia.org/tags/utilityLib" %>
<%@ taglib prefix="ui" uri="http://www.jahia.org/tags/uiComponentsLib" %>

<%--@elvariable id="currentNode" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="currentResource" type="org.jahia.services.render.Resource"--%>
<%--@elvariable id="out" type="java.io.PrintWriter"--%>
<%--@elvariable id="renderContext" type="org.jahia.services.render.RenderContext"--%>
<%--@elvariable id="script" type="org.jahia.services.render.scripting.Script"--%>
<%--@elvariable id="scriptInfo" type="java.lang.String"--%>
<%--@elvariable id="url" type="org.jahia.services.render.URLGenerator"--%>
<%--@elvariable id="workspace" type="java.lang.String"--%>
<%--@elvariable id="flowExecutionUrl" type="java.lang.String"--%>
<%--@elvariable id="mailchimp" type="org.jahia.modules.mailchimp.service.MailChimpSettings"--%>

<template:addResources type="css" resources="admin-bootstrap.css"/>
<template:addResources type="css" resources="datatables/css/bootstrap-theme.css"/>
<template:addResources type="javascript" resources="jquery.min.js"/>
<template:addResources type="javascript" resources="admin-bootstrap.js"/>
<template:addResources type="javascript" resources="jquery-ui.min.js,jquery.blockUI.js,workInProgress.js"/>
<template:addResources type="javascript"
                       resources="datatables/jquery.dataTables.js,i18n/jquery.dataTables-${currentResource.locale}.js,datatables/dataTables.bootstrap-ext.js"/>
<template:addResources type="javascript" resources="moment.min.js"/>

<%@include file="../i18n.inc"%>

<template:addResources>
    <script type="text/javascript">
        function submitCampaignSetForm(act, camp) {
            $('#campaignSetFormAction').val(act);
            if (camp) {
                $('#campaignSetFormSelected').val(camp);
            }
            $.fancybox.showLoading();
            $('#campaignSetForm').submit();
        }
    </script>
</template:addResources>

<form action="${flowExecutionUrl}" method="post" style="display: inline;" id="campaignSetForm">
    <input type="hidden" name="selectedCampaignSet" id="campaignSetFormSelected"/>
    <input type="hidden" name="_eventId" id="campaignSetFormAction"/>
</form>


<h2><fmt:message key="jmcim_campaigns.title"/> <a href="https://${mailchimp.apiPrefix}admin.mailchimp.com/campaigns/" target="_blank">MailChimp</a></h2>
<div class="box-1">
    <%@include file="../messages.inc" %>

    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th width="3%">#</th>
            <th><fmt:message key="jmcim_campaigns.Name"/></th>
            <th><fmt:message key="jmcim_campaigns.contentNode"/></th>
            <th>&nbsp;<fmt:message key="jmcim_campaigns.list"/>&nbsp;</th>
            <th><fmt:message key="jmcim_campaigns.scheduler"/></th>
            <th><fmt:message key="jmcim_campaigns.createDate"/></th>
            <th width="200"><fmt:message key="label.actions"/></th>
        </tr>
        </thead>
        <tbody>
        <c:set value="${jcr:getChildrenOfType(mailchimp.campaignsNode,'jmcim:CampaignSet')}" var="campaigns"/>
        <c:if test="${empty campaigns }">
            <tr>
                <td colspan="7"><fmt:message key="label.noItemFound"/></td>
            </tr>
        </c:if>
        <c:forEach items="${campaigns}" var="campaign" varStatus="loopStatus">
            <c:set value="${campaign.properties['contentNode'].node}" var="contentNode"/>
            <c:set value="${campaign.properties['list'].node}" var="listNode"/>
            <tr>
                <td>${loopStatus.count}</td>
                <td><a title="${campaign.properties['jcr:title'].string}" href="#showCampaigns" onclick="submitCampaignSetForm('showCampaigns', '${campaign.identifier}');return false;">${campaign.properties['jcr:title'].string}</a></td>
                <td><a title="${i18nEditMode}-${contentNode.displayableName}" href="${url.baseEdit}${contentNode.path}.html">${contentNode.displayableName}</a></td>
                <td>${listNode.displayableName}</td>
                <td>${campaign.properties['scheduler'].string}</td>
                <td><fmt:formatDate value="${campaign.properties['jcr:created'].date.time}" pattern="yyyy-MM-dd HH:mm"/></td>
                <td width="30%">
                    <c:if test="${!campaign.properties['wasSend'].string}">
                    <a style="margin-bottom:0;" class="btn btn-small" title="${i18nEdit}" href="#edit"
                       onclick="submitCampaignSetForm('editCampaignSet', '${campaign.identifier}');return false;">
                        <i class="icon-pencil"></i>
                    </a>
                    </c:if>
                    <a style="margin-bottom:0;" class="btn btn-small" title="${i18nEditMode}" href="#showCampaigns"
                       onclick="submitCampaignSetForm('showCampaigns', '${campaign.identifier}');return false;" >
                        <i class="icon-info-sign"></i>
                    </a>
                    <a style="margin-bottom:0;" class="btn btn-small" title="${i18nCampaignCreate}" href="#createCampaign"
                       onclick="submitCampaignSetForm('createCampaign', '${campaign.identifier}');return false;">
                        <i class="icon-file"></i>
                    </a>

                    <a style="margin-bottom:0;" class="btn btn-small" title="${i18nEditMailChimp}" href="https://${mailchimp.apiPrefix}admin.mailchimp.com/campaigns/show?id=${campaign.properties['templateCampaignWebId'].string}" target="_blank">
                        <i class="icon-share-alt"></i>
                    </a>
                    <c:if test="${!campaign.properties['wasSend'].string}">
                    <a class="btn btn-small"
                       onclick="{submitCampaignSetForm('updateCampaignSetContent', '${campaign.identifier}');} return false;" href="#updateCampaignSetContent"
                       title="Update content" style="margin-bottom:0;">
                        <i class="icon-refresh"></i>
                    </a>
                    </c:if>
                    <a style="margin-bottom:0;" class="btn btn-danger btn-small" title="${i18nRemove}"
                       href="#delete"
                       onclick="if (confirm('${i18nRemoveConfirm}')) {submitCampaignSetForm('removeCampaignSet', '${campaign.identifier}');} return false;">
                        <i class="icon-remove icon-white"></i>
                    </a>
                </td>
            </tr>
        </c:forEach>
        </tbody>
    </table>

    <div class="buttons">
        <button id="addCampaign" type="button" class="btn btn-primary"
                onclick="submitCampaignSetForm('createCampaignSet');">
            <i class="icon-plus icon-white"> </i><fmt:message key="jmcim_campaigns.add"/></button>
        <div class="clear"></div>
    </div>
</div>